### ISSUE TITLE
Suggestion regarding visibility status on-join

### ISSUE THREAD

**Issue by Elijeh** [tomudding/Player-Visibility#10]
**Issues:**
 - ~~When you change the "switch" message in the config, it will not update in-game.~~ (fixed, see [v2.4](https://github.com/tomudding/Player-Visibility/tree/v2.4))
 - ~~Prefix doesn't appear in the "already on/off" messages.~~ (fixed, see [v2.4](https://github.com/tomudding/Player-Visibility/tree/v2.4))
 - ~~When I have the on & off item set to an ender pearl or eye of ender then I click the item in-game, it won't deny me from using the item.~~ (fixed, see [v2.4](https://github.com/tomudding/Player-Visibility/tree/v2.4))

**Suggestions:**
 - ~~Multiple lines of lore for the on & off item.~~ (added, see [v2.4](https://github.com/tomudding/Player-Visibility/tree/v2.4))
 - Option to disable the visibility status on-join. (**need more information**)
 - ~~Just remove the "switch" message, don't like it.~~ (works as intended)

**Comment by tomudding** [comment]
I am looking into your suggestions, might take some time to update everything. 

Edit: @Elijeh could you clarify what you mean with "Option to disable the visibility status on-join."? Disable default status, like always on or off on-join...

**Comment by tomudding** [comment]
Fixed in v2.4.

**Comment by tomudding** [comment]
@Elijeh I need more information about your second suggestion, I have fixed all issues you listed and the download ([v2.4](https://github.com/tomudding/Player-Visibility/tree/v2.4)) is available via Bukkit.

**Comment by Elijeh** [comment]
When I join the server then it will send a message saying if players are visible or not.
https://gyazo.com/e3452c4d2ccf5d61eaaa32c1fecf6280.png
 
And I do think you should at least add an option to disable the switch message, I think it's spammy in my opinion.

**Comment by tomudding** [comment]
I'll add two options, one to disable the message on join (both on and off) and another one to disable the switch message.

**Comment by Elijeh** [comment]
Any updates as to when this will be added & released?

**Comment by tomudding** [comment]
I am almost done, need to test some of the things I have added, just to make sure it won't break. 

I'll release a new version before the end of this week (probably Wednesday/Thursday).

**Comment by Elijeh** [comment]
Alright

**Comment by tomudding** [comment]
Can't push an update at the moment because I have some problems with the plugin (it breaks when it shouldn't).

<s>I aim for an update tomorrow.</s>

**Edit: I now know why my plugin breaks and because of that further development is halted for an unknown amount of time, due to a bug I have found in Spigot preventing me to continue development at the moment.**

I have everything ready (all your requested functions and some bug fixes), only this one little (very important) problem-ish thing prevents me from releasing any kind of update.

**Comment by Elijeh** [comment]
Oh alright, I hope you can figure out some sort of way to fix the issue.

**Comment by tomudding** [comment]
I have submitted the newest version to BukkitDev, it should be approved very soon.

**Comment by tomudding** [comment]
I have submitted the newest version to BukkitDev, it should be approved very soon.
