### ISSUE TITLE
No Config Or File?

### ISSUE THREAD

**Issue by TexorYT** [tomudding/Player-Visibility#14]
I downloaded this and restarted my server.
there is no new plugin folder, no config file, please help

**Comment by tomudding** [comment]
Hi, sorry for my late response but I am on a holiday at the moment.

To diagnose your issue I'll need some more information, the Minecraft version, the plugin version you are using and any startup logs related to the plugin.

I'll look into it after I get home next week. If you are using Minecraft 1.12 the plugin will probably not work (need to fix that but as I said earlier I am currently on vacation).

**Comment by tomudding** [comment]
I am back home and identified the issue, I'll release an update before tomorrow. Thanks for sharing this with me, I kinda forgot this problem existed.

**Comment by tomudding** [comment]
After testing the plugin I have come across several other game breaking bugs that need to be resolved before publishing an update. ~~Sorry for the inconvenience but I'll have to push the release date back by a day.~~

**Edit**: I'll release a fix today. Doing some final testing at the moment to make sure everything works.

**Comment by tomudding** [comment]
I have submitted the update for review to Bukkit. ~~It should appear as v2.5.3 soon.~~ The update has been approved, you can download v2.5.3 from Bukkit.
