### ISSUE TITLE
Code Readability 

### ISSUE THREAD

**Issue by bramhaag** [tomudding/Player-Visibility#2]
A quick glance over the [Commands ](https://github.com/tomudding/Player-Visibility/blob/master/bukkit/src/nl/tomudding/plugins/visibility/commands/Commands.java) class reveals an issue. The readability of the code.

To be more specific: nested if-statements (if statements inside of an if statement). It's extremely messy, but we've all nested if statements in the past. 

I recently came across [this video](https://www.youtube.com/watch?v=ldqDpmMkXgw) by codecourse. He gives great examples in this vide. While the language he shows this in is PHP, it also applies to Java and other programming languages. 

I'd recommend preventing nested if-statements as much as possible.

**Comment by tomudding** [comment]
I'll (try to) clean up the code with the next update.

**Comment by tomudding** [comment]
Fixed in #7
